apply plugin: "com.github.johnrengelman.shadow"

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common

    if (project.configurations.findByName("developmentFabric")) {
        developmentFabric.extendsFrom common
    }
    if (project.configurations.findByName("developmentNeoForge")) {
        developmentNeoForge.extendsFrom common
    }

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

processResources {
    var replaceProperties = [
            "version": project.version,
            "mod_id": project.mod_id,
            "mod_name": project.mod_name,
            "mod_description": project.mod_description,
            "mod_author": project.mod_author,
            "mod_license": project.mod_license,
            "mod_website": project.mod_website,
            "mod_repository": project.mod_repository,
            "minecraft_version": project.minecraft_version,
            "fabric_loader_version": project.fabric_loader_version,
            "fabric_api_version": project.fabric_api_version,
            "neoforge_version": project.neoforge_version,
            "architectury_version": project.architectury_version,
            "yamlconfig_version": project.yamlconfig_version
    ]
    inputs.properties replaceProperties

    filesMatching(['fabric.mod.json', 'META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

shadowJar {
    relocate "org.sqlite", "gl_sqlite", {
        exclude "org/sqlite/native/**"
        exclude "og/sqlite/util/ProcessRunner.class"
    }

    relocate "jdbc:sqlite", "jdbc:gl_sqlite"

    transform(NativeTransformer.class) {
        rootDir = project.rootDir
        relocateNative "org/sqlite", "gl_sqlite"
        relocateNative "org_sqlite", "gl_1sqlite"
    }

    relocate "com.mysql", "gl_mysql"

    configurations = [project.configurations.shadowBundle]
    archiveClassifier = project.name + "-dev-shadow"

    mergeServiceFiles()
}

remapJar {
    injectAccessWidener = true
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier = null
}

task renameJarForPublication(type: Zip, dependsOn: remapJar) {
    from remapJar.archiveFile.map { zipTree(it) }
    archiveExtension = "jar"
    metadataCharset "UTF-8"
    destinationDirectory = base.libsDirectory
    archiveClassifier = project.name
}

assemble.dependsOn renameJarForPublication

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

remapSourcesJar {
    archiveClassifier = project.name + "-sources"
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}