apply plugin: "me.shedaniel.unified-publishing"

unifiedPublishing {
    project {
        displayName = "${mod_name} Fabric ${minecraft_version} - ${mod_version}"
        version = mod_version
        changelog = rootProject.file("changelog.md").exists() ? rootProject.file("changelog.md").text : "No changelog provided."
        releaseType = release_type
        gameVersions = supported_minecraft_versions.split(",").toList()
        gameLoaders = ["fabric"]

        mainPublication tasks.shadowJar

        var cursetoken = System.getenv("CURSEFORGE_API_KEY")
        if (cursetoken != null) {
            curseforge {
                token = cursetoken
                id = curse_forge_project_id
                gameVersions.addAll "Java 25"
                relations {
                    curse_forge_dependencies.split(",").each { depends it }
                }
            }
        }

        var modrinthtoken = System.getenv("MODRINTH_API_KEY")
        if (modrinthtoken != null) {
            modrinth {
                token = modrinthtoken
                id = modrinth_project_id
                relations {
                    modrinth_dependencies.split(",").each { depends it }
                }
            }
        }
    }
}
