plugins {
    id "com.github.johnrengelman.shadow"
    id "com.hypherionmc.modutils.modpublisher" version "2.1.8"
}

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modApi "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
    // Remove the next line if you don't want to depend on the API
    modApi "dev.architectury:architectury-fabric:${rootProject.architectury_version}"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowBundle project(path: ":common", configuration: "transformProductionFabric")

    include annotationProcessor(implementation("io.github.llamalad7:mixinextras-fabric:${rootProject.mixin_extras_version}"))

    modImplementation "org.xerial:sqlite-jdbc:${project.sqlite_version}"
    shadowBundle "org.xerial:sqlite-jdbc:${project.sqlite_version}"

    modImplementation "com.mysql:mysql-connector-j:${project.mysql_version}"
    shadowBundle "com.mysql:mysql-connector-j:${project.mysql_version}"

    modImplementation "maven.modrinth:supermartijn642s-config-lib:${rootProject.config_library_version_fabric}"

    modCompileOnly "me.lucko:fabric-permissions-api:${rootProject.permissions_api_version_fabric}"
}

processResources {
    var replaceProperties = [
            "version": project.version,
            "mod_id": project.mod_id,
            "mod_name": project.mod_name,
            "mod_description": project.mod_description,
            "mod_author": project.mod_author,
            "mod_license": project.mod_license,
            "mod_website": project.mod_website,
            "mod_repository": project.mod_repository,

            "minecraft_version": project.minecraft_version,
            "architectury_version": project.architectury_version,
            "config_library_version": project.config_library_version_fabric.split('-')[0].replaceAll(/(\d)([a-zA-Z])$/, '$1+$2')
    ]
    inputs.properties replaceProperties

    filesMatching(['fabric.mod.json']) {
        expand replaceProperties
    }
}

shadowJar {
    relocate "org.sqlite", "gl_sqlite", {
        exclude "org/sqlite/native/**"
        exclude "og/sqlite/util/ProcessRunner.class"
    }

    relocate "jdbc:sqlite", "jdbc:gl_sqlite"

    transform(NativeTransformer.class) {
        rootDir = project.rootDir
        relocateNative "org/sqlite", "gl_sqlite"
        relocateNative "org_sqlite", "gl_1sqlite"
    }

    relocate "com.mysql", "gl_mysql"

    configurations = [project.configurations.shadowBundle]
    archiveClassifier = "fabric-dev-shadow"

    mergeServiceFiles()
}

remapJar {
    injectAccessWidener = true
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier = null
}

task renameJarForPublication(type: Zip, dependsOn: remapJar) {
    from remapJar.archiveFile.map { zipTree(it) }
    archiveExtension = "jar"
    metadataCharset "UTF-8"
    destinationDirectory = base.libsDirectory
    archiveClassifier = project.name
}


assemble.dependsOn renameJarForPublication

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

remapSourcesJar {
    archiveClassifier = "fabric-sources"
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenFabric(MavenPublication) {
            groupId = rootProject.maven_group
            artifactId = rootProject.archives_base_name + "-fabric"
            from components.java
        }
    }

    repositories {
        maven {
            url = project.version.contains('-PR') ? 'https://maven.daqem.com/snapshots' : 'https://maven.daqem.com/releases'
            credentials {
                username = System.getenv("MAVEN_USER")
                password = System.getenv("MAVEN_PASS")
            }
        }
    }
}

publisher {
    apiKeys {
        modrinth System.getenv("MODRINTH_TOKEN")
        curseforge System.getenv("CURSE_TOKEN")
        github System.getenv("GITHUB_TOKEN")
    }

    setCurseID(project.curse_forge_project_id)
    setModrinthID(project.modrinth_project_id)
    setChangelog(rootProject.file("changelog.md"))
    setVersionType(project.release_type)

    setGameVersions(project.supported_minecraft_versions.split(",").collect { it.trim() })
    setJavaVersions(["Java 17"])

    setVersion(project.mod_version)
    setDisplayName("${project.mod_name} Fabric ${project.minecraft_version} - ${project.mod_version}")

    modrinthDepends {
        project.modrinth_dependencies.split(",").each {
            required(it.trim())
        }
    }
    curseDepends {
        project.curseforge_dependencies.split(",").each {
            required(it.trim())
        }
    }

    setArtifact(tasks.remapJar)
    addAdditionalFile(tasks.remapSourcesJar)
}