org.gradle.jvmargs=-Xmx4096M
org.gradle.daemon=false
java_version=25

# Project Info
group=com.daqem.grieflogger
version=21.1.2
mod_id=grieflogger
mod_name=GriefLogger
mod_description=A mod that logs all player interactions with blocks and entities and stores them in a database.
mod_author=DAQEM
mod_license=Apache-2.0
mod_website=https://daqem.com
mod_repository=https://github.com/DAQEM/GriefLogger

# Publishing
supported_minecraft_versions=26.2
release_type=release
curse_forge_project_id=435029
curse_forge_dependencies=knot,yaml-config
modrinth_project_id=8oGVUFuX
modrinth_dependencies=knot,yaml-config

# Dependencies
minecraft_version=26.2
neo_form_version=26.2-2
knot_version=21.2.2
uilib_version=21.1.1
yamlconfig_version=21.1.0
sqlite_version=3.53.2.1
mysql_version=9.7.0

# Fabric
fabric_version=0.156.0+26.2
fabric_loader_version=0.19.3

# NeoForge
neoforge_version=26.2.0.37-beta


