org.gradle.jvmargs=-Xmx4096M

enabled_platforms=fabric,neoforge
maven_group=com.daqem.grieflogger
archives_base_name=grieflogger

# Project
mod_version=19.0.0-PR1
mod_id=grieflogger
mod_name=GriefLogger
mod_description=A mod that logs all player interactions with blocks and entities and stores them in a database.
mod_author=DAQEM
mod_license=Apache-2.0
mod_website=https://daqem.com
mod_repository=https://github.com/DAQEM/GriefLogger

# Publishing
supported_minecraft_versions=1.21.11
release_type=release

curse_forge_project_id=435029
curseforge_dependencies=architectury-api,yaml-config

modrinth_project_id=8oGVUFuX
modrinth_dependencies=architectury-api,yaml-config

# Minecraft
minecraft_version=1.21.11

# Fabric
fabric_loader_version=0.18.3
fabric_api_version=0.140.0+1.21.11

# NeoForge
neoforge_version=21.11.0-beta
neoforge_loader_version=1

# Dependencies
architectury_version=19.0.1
config_library_version=19.0.0-PR1
sqlite_version=3.47.2.0
mysql_version=8.4.0

# Runtime Only
ui_library_version=19.0.0-PR1


