plugins {
    id "com.github.johnrengelman.shadow" version "7.1.2"
    id "com.matthewprenger.cursegradle" version "1.4.0"
    id "com.modrinth.minotaur" version "2.+"
}

architectury {
    platformSetupLoomIde()
    forge()
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath

    forge {
        convertAccessWideners = true
        extraAccessWideners.add loom.accessWidenerPath.get().asFile.name

        mixinConfig "grieflogger-common.mixins.json"
        mixinConfig "grieflogger.mixins.json"
    }
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin since it *excludes* files.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common
}

dependencies {
    forge "net.minecraftforge:forge:${rootProject.forge_version}"
    // Remove the next line if you don't want to depend on the API
    modApi "dev.architectury:architectury-forge:${rootProject.architectury_version}"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionForge")) { transitive = false }

    modImplementation "org.xerial:sqlite-jdbc:3.47.2.0"
    shadowCommon "org.xerial:sqlite-jdbc:3.47.2.0"

    modImplementation "com.mysql:mysql-connector-j:8.4.0"
    shadowCommon "com.mysql:mysql-connector-j:8.4.0"

    modImplementation "curse.maven:supermartijn642s-config-lib-438332:${project.config_library_file_forge}-forge-mc${project.minecraft_version.split('\\\\.')[0..1].join('.')}"
}

processResources {
    var replaceProperties = [
            "version": project.version,
            "mod_id": project.mod_id,
            "mod_name": project.mod_name,
            "mod_description": project.mod_description,
            "mod_author": project.mod_author,
            "mod_license": project.mod_license,
            "mod_website": project.mod_website,
            "mod_repository": project.mod_repository,

            "supported_forge_modloader_version": project.supported_forge_modloader_version,
            "minecraft_version": project.minecraft_version,
            "architectury_version": project.architectury_version,
            "config_library_version": project.config_library_version_forge
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml']) {
        expand replaceProperties
    }
}

shadowJar {
    relocate "org.sqlite", "gl_sqlite", {
        exclude "org/sqlite/native/**"
        exclude "og/sqlite/util/ProcessRunner.class"
    }

    relocate "jdbc:sqlite", "jdbc:gl_sqlite"

    transform(NativeTransformer.class) {
        rootDir = project.rootDir
        relocateNative "org/sqlite", "gl_sqlite"
        relocateNative "org_sqlite", "gl_1sqlite"
    }

    relocate "com.mysql", "gl_mysql"

    configurations = [project.configurations.shadowBundle]
    archiveClassifier = "forge-dev-shadow"

    mergeServiceFiles()
}

remapJar {
    inputFile.set shadowJar.archiveFile
    atAccessWideners.add loom.accessWidenerPath.get().asFile.name
    archiveClassifier = null
}

task renameJarForPublication(type: Zip, dependsOn: remapJar) {
    from remapJar.archiveFile.map { zipTree(it) }
    archiveExtension = "jar"
    metadataCharset "UTF-8"
    destinationDirectory = base.libsDirectory
    archiveClassifier = project.name
}

assemble.dependsOn renameJarForPublication

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

remapSourcesJar {
    archiveClassifier = "forge-sources"
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenForge(MavenPublication) {
            groupId = rootProject.maven_group
            artifactId = rootProject.archives_base_name + "-forge"
            from components.java
        }
    }

    repositories {
        maven {
            url = project.version.contains('-PR') ? 'https://maven.daqem.com/snapshots' : 'https://maven.daqem.com/releases'
            credentials {
                username = System.getenv("MAVEN_USER")
                password = System.getenv("MAVEN_PASS")
            }
        }
    }
}

curseforge {
    apiKey = System.getenv("CURSEFORGE_API_KEY")
    project {
        id = project.curse_forge_project_id
        releaseType = project.release_type
        changelogType = "markdown"
        changelog = rootProject.file('changelog.md')

        project.supported_minecraft_versions.split(',').each { version ->
            addGameVersion version
        }

        addGameVersion "Java 17"
        addGameVersion "Forge"

        relations {
            project.curseforge_dependencies.split(',').each { dep ->
                requiredDependency dep.trim()
            }
        }

        mainArtifact(remapJar) {
            displayName = "$project.mod_name Forge $project.minecraft_version - $project.mod_version"
        }

        addArtifact(remapSourcesJar) {
        }
    }
}

modrinth {
    token = System.getenv("MODRINTH_API_KEY")
    projectId = project.modrinth_project_id
    versionName = "$project.mod_name Forge $project.minecraft_version - $project.mod_version"
    versionNumber = "$project.mod_version"
    versionType = "$project.release_type"
    uploadFile = remapJar
    additionalFiles = [remapSourcesJar]
    gameVersions = project.supported_minecraft_versions.split(',').toList()
    loaders = ["forge"]
    changelog = rootProject.file('changelog.md').text
    dependencies {
        project.modrinth_dependencies.split(',').each { dep ->
            required.project dep
        }
    }
}