FROM eclipse-temurin:25-jdk AS jdk

FROM redhat/ubi9-minimal
ENV JAVA_HOME=/opt/java/openjdk
ENV PATH="${JAVA_HOME}/bin:${PATH}"
COPY --from=jdk $JAVA_HOME $JAVA_HOME

RUN microdnf install -y python3 && microdnf clean all

WORKDIR /server

COPY test_server.py /test_server.py

CMD ["python3", "/test_server.py"]