services:
  test-ubuntu:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    volumes:
      - ..:/app:ro

  test-debian:
    build:
      context: .
      dockerfile: Dockerfile.debian
    volumes:
      - ..:/app:ro

  test-alpine:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    volumes:
      - ..:/app:ro

  test-rhel:
    build:
      context: .
      dockerfile: Dockerfile.rhel
    volumes:
      - ..:/app:ro

  test-windows:
    build:
      context: .
      dockerfile: Dockerfile.windows
    volumes:
      - ..:/app:ro

  test-macos:
    build:
      context: .
      dockerfile: Dockerfile.verify-macos
    volumes:
      - ..:/app:ro