FROM eclipse-temurin:25-jdk AS jdk

FROM debian:bookworm-slim
ENV JAVA_HOME=/opt/java/openjdk
ENV PATH="${JAVA_HOME}/bin:${PATH}"
COPY --from=jdk $JAVA_HOME $JAVA_HOME

RUN apt-get update && apt-get install -y python3 curl && rm -rf /var/lib/apt/lists/*

WORKDIR /server

COPY test_server.py /test_server.py

CMD ["python3", "/test_server.py"]