architectury {
    common(rootProject.enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/${rootProject.mod_id}.accesswidener")
}

apply from: rootProject.file("gradle/scripts/maven-publishing.gradle")

dependencies {
    // Fabric loader for annotations/mixins (Architectury standard)
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modApi "dev.architectury:architectury:${project.architectury_version}"
    modImplementation "com.daqem.yamlconfig:yamlconfig-common:${project.yamlconfig_version}"
}