modLoader = "javafml"
loaderVersion = "[7,)"
#issueTrackerURL = ""
license = "Apache-2.0"

[[mods]]
modId = "grieflogger"
version = "${version}"
displayName = "GriefLogger"
authors = "DAQEM"
description = '''
A mod that logs all player interactions with blocks and entities and stores them in a database.
'''
#logoFile = ""

[[dependencies.grieflogger]]
modId = "neoforge"
mandatory = true
versionRange = "[3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.grieflogger]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.grieflogger]]
modId = "architectury"
mandatory = true
versionRange = "[15.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.grieflogger]]
modId = "yamlconfig"
mandatory = true
versionRange = "[${config_library_version},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "grieflogger-common.mixins.json"